# Generated by Django 2.1 on 2019-01-22 01:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('blog', '0003_auto_20181206_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='quote',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
    ]
