# Generated by Django 2.1 on 2019-01-22 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('blog', '0005_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
    ]
